// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vylrzzqvfjqihphozgpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5bHJ6enF2ZmpxaWhwaG96Z3BvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mzk5ODgsImV4cCI6MjA2NTUxNTk4OH0.k6azX92g3oF150RkLeGB23kc8WM_YrdqirYkBpZDV88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);